# Generated by Django 5.2.7 on 2025-10-19 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="idea",
            name="embedding",
        ),
        migrations.AddField(
            model_name="idea",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="idea",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="idea",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ideas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
