# Generated by Django 5.2.7 on 2025-10-20 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0003_remove_idea_updated_at_idea_category_idea_keywords_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("semantic", "Semantic"), ("manual", "Manual")],
                        default="semantic",
                        max_length=50,
                    ),
                ),
                ("strength", models.FloatField(default=0.5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_connections",
                        to="ideas.idea",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_connections",
                        to="ideas.idea",
                    ),
                ),
            ],
            options={
                "unique_together": {("source", "target", "type")},
            },
        ),
    ]
