# Generated by Django 5.2.7 on 2025-10-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0004_connection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="strength",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="connection",
            name="type",
            field=models.CharField(default="related", max_length=50),
        ),
    ]
