# Generated by Django 5.2.7 on 2025-10-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0005_alter_connection_strength_alter_connection_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="embedding",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="idea",
            name="used_for_training",
            field=models.BooleanField(default=False),
        ),
    ]
